export const countries = {
  japan: {
    name: "일본",
    flag: "🇯🇵",
    color: "#ff5a7a",
    subtitle: "예절과 기본 회화 중심",
    lessons: [
      {
        type: "팁",
        title: "예절",
        fact: "센소지는 도쿄에서 가장 오래된 사찰입니다.",
        question: "센소지에 들어가기 전, 많은 일본 사람들이 입구에서 가볍게 허리를 숙이는 이유는 무엇일까요?",
        options: [
          "신성한 공간에 대한 존중을 표현하기 위해",
          "신에게 자신의 소원을 크게 알리기 위해",
          "사진을 잘 찍기 위해",
        ],
        answer: 0,
      },
      {
        type: "문화",
        title: "붉은 문, 도리이",
        fact: "교토에 위치한 신사입니다.",
        question: "후시미 이나리 신사의 붉은 문(도리이)은 무엇을 의미할까요?",
        options: ["신의 세계와 인간 세계를 구분하는 경계이다.", "일본 왕족만 지나갈 수 있는 문이다.", "악귀를 가두는 감옥이다."],
        answer: 0,
      },
      {
        type: "문화",
        title: "아경이 아름다운 히메지성",
        fact: "히메지성은 목조 건물의 최고 걸작입니다.",
        question: "히메지성 내부 계단이 일부러 매우 가파르고 좁게 만들어진 가장 큰 이유는 무엇일까요?",
        options: ["적이 성 안으로 들어와도 빠르게 이동하지 못하게 하기 위해", "당시에는 계단 기술이 부족했기 때문에", "무거운 짐을 쉽게 옮기기 위해"],
        answer: 0,
      },
    ],
    emergency: "경찰 110 / 구급·화재 119",
  },
  france: {
    name: "프랑스",
    flag: "🇫🇷",
    color: "#4169e1",
    subtitle: "인사 예절과 카페 문화",
    lessons: [
      {
        type: "팁",
        title: "프랑스 팁 문화",
        fact: "프랑스는 서비스 요금이 포함된 경우가 많지만, 만족했다면 소액을 남기기도 해요.",
        question: "프랑스에서 팁은 보통 어떻게 하나요?",
        options: [
          "필수는 아니지만 소액 가능",
          "항상 30%",
          "절대 계산하지 않는다",
        ],
        answer: 0,
      },
      {
        type: "문화",
        title: "루브르 박물관",
        fact: "루브르는 세계적으로 유명한 박물관이며, 프랑스 역사와 예술을 대표해요.",
        question: "루브르가 유명한 이유는?",
        options: ["박물관과 예술", "온천", "만리장성"],
        answer: 0,
      },
      {
        type: "언어",
        title: "봉주르",
        fact: "프랑스에서는 가게에 들어갈 때 Bonjour라고 먼저 인사하는 것이 좋아요.",
        question: "프랑스어 기본 인사는?",
        options: ["Bonjour", "Hola", "Ni hao"],
        answer: 0,
      },
    ],
    emergency: "유럽 공통 긴급번호 112",
  },
  uk: {
    name: "영국",
    flag: "🇬🇧",
    color: "#7c5cff",
    subtitle: "줄서기와 왕실 문화",
    lessons: [
      {
        type: "팁",
        title: "영국 매너",
        fact: "영국에서는 줄서기 문화가 강하고, 새치기는 매우 무례하게 여겨져요.",
        question: "영국에서 특히 조심해야 할 매너는?",
        options: ["줄서기 지키기", "큰 소리로 통화하기", "가격 흥정하기"],
        answer: 0,
      },
      {
        type: "문화",
        title: "런던 타워",
        fact: "런던 타워는 영국 왕실과 중세 역사를 보여주는 대표 유적이에요.",
        question: "런던 타워는 무엇과 관련이 깊을까요?",
        options: ["왕실과 역사", "피라미드", "벚꽃 축제"],
        answer: 0,
      },
      {
        type: "언어",
        title: "Polite English",
        fact: "영국에서는 please, sorry, thank you 같은 정중한 표현을 자주 써요.",
        question: "정중하게 부탁할 때 어울리는 표현은?",
        options: ["Please", "Adios", "Merci"],
        answer: 0,
      },
    ],
    emergency: "경찰·구급·화재 999 / 112",
  },
  spain: {
    name: "스페인",
    flag: "🇪🇸",
    color: "#ff9f1c",
    subtitle: "식사 시간과 인사 표현",
    lessons: [
      {
        type: "팁",
        title: "스페인 식사 문화",
        fact: "스페인은 저녁 식사 시간이 비교적 늦은 편이에요.",
        question: "스페인 여행 중 식사 문화로 알맞은 것은?",
        options: ["저녁이 늦은 편이다", "아침만 먹는다", "팁이 법으로 필수다"],
        answer: 0,
      },
      {
        type: "문화",
        title: "사그라다 파밀리아",
        fact: "바르셀로나의 사그라다 파밀리아는 가우디의 대표 건축물이에요.",
        question: "사그라다 파밀리아가 있는 도시는?",
        options: ["바르셀로나", "파리", "도쿄"],
        answer: 0,
      },
      {
        type: "언어",
        title: "Hola",
        fact: "Hola는 스페인어로 안녕하세요라는 뜻이에요.",
        question: "스페인어 인사는?",
        options: ["Hola", "Hello", "Bonjour"],
        answer: 0,
      },
    ],
    emergency: "유럽 공통 긴급번호 112",
  },
  china: {
    name: "중국",
    flag: "🇨🇳",
    color: "#ef4444",
    subtitle: "기본 표현과 금기 이해",
    lessons: [
      {
        type: "팁",
        title: "중국 숫자 문화",
        fact: "중국에서는 숫자 8은 좋은 의미로, 숫자 4는 꺼리는 경우가 있어요.",
        question: "중국에서 비교적 꺼리는 숫자는?",
        options: ["4", "8", "10"],
        answer: 0,
      },
      {
        type: "문화",
        title: "만리장성",
        fact: "만리장성은 중국을 대표하는 역사 유적 중 하나예요.",
        question: "만리장성은 어느 나라의 대표 유적일까요?",
        options: ["중국", "영국", "스페인"],
        answer: 0,
      },
      {
        type: "언어",
        title: "니하오",
        fact: "Ni hao는 중국어로 안녕하세요라는 뜻이에요.",
        question: "중국어 기본 인사는?",
        options: ["Ni hao", "Merci", "Gracias"],
        answer: 0,
      },
    ],
    emergency: "경찰 110 / 구급 120 / 화재 119",
  },
};
